import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./store/store-provider";
import { Toaster } from "react-hot-toast";
import TawkToChat from "@/shared/components/tawk-chat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // ✅ добавь это
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap", // ✅ добавь это
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <StoreProvider>
          <div className="container m-auto p-auto">
            {children}
            <TawkToChat/>
          </div>
          <Toaster position="top-center" reverseOrder={false}/>
        </StoreProvider>
      </body>
    </html>
  );
}
